### ISSUE TITLE
xvfb-run: error: Xvfb failed to start when building Dockerfile

### ISSUE THREAD

**Issue by shankiesan** [msokk/electron-render-service#37] opened 2017-03-10 12:26 UTC
Ooh! Here's an issue that I have no idea how to solve!

When I use the built image on [Docker Hub](https://hub.docker.com/r/msokk/electron-render-service/) that was built 9 days ago, all works well. But if I build from the Dockerfile using `docker build -t electron-render-service .` ...

and then run it:

`docker run -it electron-render-service`

I get: `xvfb-run: error: Xvfb failed to start`

Any ideas?

**Comment by shankiesan** [comment] 2017-03-10 12:29
Looks like some dependencies updating or something...

**Comment by Reggino** [comment] 2017-03-10 13:01
Probably dupe of #31. You can probably rebuild the container to work around this issue

**Comment by shankiesan** [comment] 2017-03-10 18:43
Thanks @Reggino but I don't think it is – I have the same problem if I force remove the container or even build on a fresh host. I could be wrong though!

**Comment by msokk** [comment] 2017-03-12 10:31
@shankiesan Could you try 0.10.0 from Dockerhub?

**Comment by shankiesan** [comment] 2017-03-13 10:26
@msokk Yep, that sorted it. I'm glad you did that, I wouldn't have been able to work out all the bits that went wrong!

**Closed** 2017-03-24 09:01 UTC
Labels: bug
